---
- name: Update apt cache and upgrade all packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
  register: upgrade_debian_apt_upgrade_result

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: upgrade_debian_reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: upgrade_debian_reboot_required_file.stat.exists
