---
- name: Load inventory from Terraform
  import_playbook: playbooks/00_setup_inventory.yaml

- name: Install pgAdmin4
  hosts: clusters
  become: true
  environment:
    KUBECONFIG: "{{ custom_kubeconfig }}"
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ custom_kubeconfig }}"
  roles:
    - role: pgadmin
